# Generated by Django 6.0.3 on 2026-04-01 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignment_attachments/', verbose_name='Вложение к заданию'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='Ответ ученика'),
        ),
        migrations.CreateModel(
            name='AnswerAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='answer_attachments/', verbose_name='Файл ответа')),
                ('title', models.CharField(max_length=200, verbose_name='Название файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.grade', verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Вложение ответа',
                'verbose_name_plural': 'Вложения ответов',
            },
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
    ]
